 (("default" . ((user-emacs-directory . "/media/chriad/nebula/spacemacs-fork")
            (env . (("SPACEMACSDIR" . "/home/chriad/.config/emacs")))))
  ("experimental" . ((user-emacs-directory . "~/spacemacs-installations/spacemacs-fork")
                (env . (("SPACEMACSDIR" . "~/spacemacs-homes/fork")))))
  )
